project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "AWS x NFL Big Data Bowl"
  author:
    - Kyle Coletta (kc3936)
    - Connor Feldman (cf3069)
  repo-url: https://github.com/colettak16/AWSxNFL-Big-Data-Bowl
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


